from pathlib import Path

from _script_env import setup_import_path

setup_import_path()

from control_plane.runtime import connect_db, ensure_runtime_dirs, load_config, repo_root, seed_nodes

def bootstrap_memory():
    """
    Reads all markdown files in live/tacit_knowledge/ and compiles them 
    into a single distilled live/MEMORY.md runtime policy file.
    """
    root = repo_root()
    tacit_dir = root / "live" / "tacit_knowledge"
    memory_file_path = root / "live" / "MEMORY.md"

    print(f"Bootstrapping runtime policy from {tacit_dir}...")

    compiled_content = "# DICTATED RUNTIME POLICY (MEMORY.md)\n\n"
    compiled_content += "*This file is auto-generated by 01_bootstrap.py. Do not edit directly.*\n\n"

    md_files = sorted(Path(tacit_dir).glob("*.md"))
    for file_path in md_files:
        filename = file_path.name
        with open(file_path, 'r', encoding='utf-8') as f:
            compiled_content += f"## Source: {filename}\n"
            compiled_content += f.read() + "\n\n"

    with open(memory_file_path, 'w', encoding='utf-8') as f:
        f.write(compiled_content)

    print(f"Successfully compiled {len(md_files)} files into MEMORY.md")

def check_env():
    env_path = repo_root() / ".env"
    if not env_path.exists():
        print("WARNING: .env file not found. Copy .env.example to .env and configure it.")
    else:
        print(".env file checks passed.")

def bootstrap_runtime():
    root = repo_root()
    ensure_runtime_dirs(root)
    config = load_config(root)
    conn = connect_db(root, config)
    seed_nodes(conn, config)
    print(f"Runtime directories ready under {root}")
    print(f"Control plane database ready at {root / config['dispatcher']['database_path']}")

if __name__ == "__main__":
    check_env()
    bootstrap_runtime()
    bootstrap_memory()
    print("Control plane bootstrap complete. Ready for heartbeat loop.")
