import os
import glob

def bootstrap_memory():
    """
    Reads all markdown files in live/tacit_knowledge/ and compiles them 
    into a single distilled live/MEMORY.md runtime policy file.
    """
    tacit_dir = os.path.join(os.path.dirname(__file__), '../../live/tacit_knowledge')
    memory_file_path = os.path.join(os.path.dirname(__file__), '../../live/MEMORY.md')
    
    print(f"Bootstrapping runtime policy from {tacit_dir}...")
    
    compiled_content = "# DICTATED RUNTIME POLICY (MEMORY.md)\n\n"
    compiled_content += "*This file is auto-generated by 01_bootstrap.py. Do not edit directly.*\n\n"

    md_files = glob.glob(os.path.join(tacit_dir, '*.md'))
    for file_path in md_files:
        filename = os.path.basename(file_path)
        with open(file_path, 'r', encoding='utf-8') as f:
            compiled_content += f"## Source: {filename}\n"
            compiled_content += f.read() + "\n\n"
            
    with open(memory_file_path, 'w', encoding='utf-8') as f:
        f.write(compiled_content)
        
    print(f"Successfully compiled {len(md_files)} files into MEMORY.md")

def check_env():
    env_path = os.path.join(os.path.dirname(__file__), '../../.env')
    if not os.path.exists(env_path):
        print("WARNING: .env file not found. Copy .env.example to .env and configure it.")
    else:
        print(".env file checks passed.")

if __name__ == "__main__":
    check_env()
    bootstrap_memory()
    print("Control plane bootstrap complete. Ready for heartbeat loop.")
